services:
  - type: web
    name: cortate-frontend
    env: static
    rootDir: ./frontend
    buildCommand: npm ci --only=production && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=86400
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://tu-backend.onrender.com/api
      - key: VITE_FRONTEND_URL
        sync: false
      - key: VITE_GOOGLE_MAPS_API_KEY
        sync: false
