services:
  - type: web
    name: cortate-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python backend/app.py"
    envVars:
      - key: SECRET_KEY
        value: super-secret-key
      - key: GOOGLE_API_KEY
        value: AIzaSyDj7gIzf_lDToiZQbMN5_XSfZCxDp_rGjg
      - key: MONGO_URI
        value: mongodb+srv://usuario:password@tubasededatos.mongodb.net/?retryWrites=true&w=majority
    autoDeploy: true
    plan: free
